### ISSUE TITLE
discord.errors.ClientException: ffmpeg was not found.

### ISSUE THREAD

**Issue by tanersb** [RB387/py-discord-music-bot#7]
This error occurs when I use the !play command. 

    raise ClientException(executable + ' was not found.') from None
discord.errors.ClientException: ffmpeg was not found.

**Comment by RB387** [comment]
Hi! You need to install ffmpeg on your computer. If you are using MacOS, you can easily do this with command 
`brew install ffmpeg`
(ffmpeg also available on Linux, Windows) 

Or just run bot in docker container
`docker build -t discord-music-bot .
docker run discord-music-bot `

**Comment by tanersb** [comment]
What version does Pyhton work on? I get too many errors.

**Comment by RB387** [comment]
The bot was developed for Python 3.8.
If errors still occur, you can always build and run a Docker container
